#!/bin/bash
echo "To get your environment variables from Vercel:"
echo ""
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Click on your project: blogfromhell"
echo "3. Go to: Settings → Environment Variables"
echo "4. Copy each value and run these commands:"
echo ""
echo "   export NEXT_PUBLIC_SUPABASE_URL='your_value_here'"
echo "   export NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY='your_value_here'"
echo "   export SUPABASE_SERVICE_ROLE_KEY='your_value_here'"
echo "   export NEXT_PUBLIC_ADMIN_PASSWORD='your_value_here'"
echo ""
echo "Then run: ./write-env.sh"
